name: minimarket
env: dev
domain: localhost
security:
  algorithm: HS256
  access_token_expire_minutes: 30
postgres:
  url: localhost:5432
  database: minimarket
  username: admin
oapi:
  oapi_path: /oapi